### ISSUE TITLE
Missing flush() method in the repositories interface ?

### ISSUE THREAD

**Issue by Lctrs** [php-xapi/repository-api#12]
Currently, the functions that stores or deletes items in our interfaces defines a `$flush` boolean parameter for committing or not the changes directly to the storage.

But the absence of a `flush()` method in the interface make it very difficult to actually delay the flush of our changes.

WDYT @xabbuh ?

**Comment by xabbuh** [comment]
Actually, I was thinking about completely getting rid of the `$flush` argument and use an approach similar to what the `CacheItemPoolInterface` from PSR-6 is doing (i.e. having methods like `save()`, `saveDeferred()`, and `commit()`). What do you think?

**Comment by Lctrs** [comment]
Looks like a more flexible solution. I'm +1 on this.

**Comment by Lctrs** [comment]
I just pushed a commit to #11 to demonstrate this.

ATM, I think it misses exceptions to be thrown when `save()`, `delete()` and `commit()` fail.

**Comment by Lctrs** [comment]
I think it also misses a `isDeferred($object)` method that returns true if the object is in a deferred state, false otherwise.

We may need it for implementing [concurrency](https://github.com/adlnet/xAPI-Spec/blob/master/xAPI-Communication.md#concurrency). But since I'm not sure, we can add it later.

**Comment by Lctrs** [comment]
@xabbuh What about a single `WriteException` to be thrown by `save()`, `delete()` and `commit()` when they fail ?

Or do you prefer 2 additional classes (eg. `SaveException` and `DeleteException`) that extends `WriteException` (which will be an abstract class then) ?

**Comment by xabbuh** [comment]
I think to be on the safe side having to exceptions which extend the `WriteException` is a better approach.

**Comment by Lctrs** [comment]
@xabbuh See latest commit in #11.
